
package com.electro.cxf.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-12T20:52:33.315+08:00
 * Generated source version: 2.7.18
 * 
 */
public final class MemberService_MemberServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.cxf.electrombile.com/", "MemberServiceService");

    private MemberService_MemberServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MemberServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MemberServiceService ss = new MemberServiceService(wsdlURL, SERVICE_NAME);
        MemberService port = ss.getMemberServicePort();  
        
        {
        System.out.println("Invoking getScopeMbilePageList...");
        com.electro.cxf.service.WeChatMember _getScopeMbilePageList_member = null;
        com.electro.cxf.service.BaseOutDomain _getScopeMbilePageList__return = port.getScopeMbilePageList(_getScopeMbilePageList_member);
        System.out.println("getScopeMbilePageList.result=" + _getScopeMbilePageList__return);


        }
        {
        System.out.println("Invoking unlockingMobile...");
        com.electro.cxf.service.WeChatMember _unlockingMobile_member = null;
        com.electro.cxf.service.BaseOutDomain _unlockingMobile__return = port.unlockingMobile(_unlockingMobile_member);
        System.out.println("unlockingMobile.result=" + _unlockingMobile__return);


        }
        {
        System.out.println("Invoking colseLockMobile...");
        com.electro.cxf.service.WeChatMember _colseLockMobile_member = null;
        com.electro.cxf.service.BaseOutDomain _colseLockMobile__return = port.colseLockMobile(_colseLockMobile_member);
        System.out.println("colseLockMobile.result=" + _colseLockMobile__return);


        }
        {
        System.out.println("Invoking sendMemberPosition...");
        java.lang.String _sendMemberPosition_adress = "";
        com.electro.cxf.service.BaseOutDomain _sendMemberPosition__return = port.sendMemberPosition(_sendMemberPosition_adress);
        System.out.println("sendMemberPosition.result=" + _sendMemberPosition__return);


        }
        {
        System.out.println("Invoking addMemberInfo...");
        com.electro.cxf.service.WeChatMember _addMemberInfo_member = null;
        com.electro.cxf.service.BaseOutDomain _addMemberInfo__return = port.addMemberInfo(_addMemberInfo_member);
        System.out.println("addMemberInfo.result=" + _addMemberInfo__return);


        }

        System.exit(0);
    }

}
