package com.electro.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-12T20:52:33.551+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.cxf.electrombile.com/", name = "MemberService")
@XmlSeeAlso({ObjectFactory.class})
public interface MemberService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getScopeMbilePageList", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.GetScopeMbilePageList")
    @WebMethod
    @ResponseWrapper(localName = "getScopeMbilePageListResponse", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.GetScopeMbilePageListResponse")
    public com.electro.cxf.service.BaseOutDomain getScopeMbilePageList(
        @WebParam(name = "member", targetNamespace = "")
        com.electro.cxf.service.WeChatMember member
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "unlockingMobile", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.UnlockingMobile")
    @WebMethod
    @ResponseWrapper(localName = "unlockingMobileResponse", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.UnlockingMobileResponse")
    public com.electro.cxf.service.BaseOutDomain unlockingMobile(
        @WebParam(name = "member", targetNamespace = "")
        com.electro.cxf.service.WeChatMember member
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "colseLockMobile", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.ColseLockMobile")
    @WebMethod
    @ResponseWrapper(localName = "colseLockMobileResponse", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.ColseLockMobileResponse")
    public com.electro.cxf.service.BaseOutDomain colseLockMobile(
        @WebParam(name = "member", targetNamespace = "")
        com.electro.cxf.service.WeChatMember member
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendMemberPosition", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.SendMemberPosition")
    @WebMethod
    @ResponseWrapper(localName = "sendMemberPositionResponse", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.SendMemberPositionResponse")
    public com.electro.cxf.service.BaseOutDomain sendMemberPosition(
        @WebParam(name = "adress", targetNamespace = "")
        java.lang.String adress
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addMemberInfo", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.AddMemberInfo")
    @WebMethod
    @ResponseWrapper(localName = "addMemberInfoResponse", targetNamespace = "http://service.cxf.electrombile.com/", className = "com.electro.cxf.service.AddMemberInfoResponse")
    public com.electro.cxf.service.BaseOutDomain addMemberInfo(
        @WebParam(name = "member", targetNamespace = "")
        com.electro.cxf.service.WeChatMember member
    );
}
